// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsVMPbUTCuXJSM32SCgphVUiqjkvXaZjI',
    appId: '1:395359887583:web:11ad21bca5255851ef496a',
    messagingSenderId: '395359887583',
    projectId: 'exchangehouse-852f7',
    authDomain: 'exchangehouse-852f7.firebaseapp.com',
    storageBucket: 'exchangehouse-852f7.firebasestorage.app',
    measurementId: 'G-Q9PKY2TN3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsXp_beljXgffLz8_lq7yk459iwcD1gxM',
    appId: '1:395359887583:android:30df1e28bf0508adef496a',
    messagingSenderId: '395359887583',
    projectId: 'exchangehouse-852f7',
    storageBucket: 'exchangehouse-852f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp7nYBaA32I1x5KgbY-m05H-e7N3vRDxw',
    appId: '1:395359887583:ios:a2531cbb04739f9aef496a',
    messagingSenderId: '395359887583',
    projectId: 'exchangehouse-852f7',
    storageBucket: 'exchangehouse-852f7.firebasestorage.app',
    iosBundleId: 'com.example.exchangeDarr',
  );
}
